VERSION = "2.0.0"

NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS = [
  "GDRLJC6EOKRR3BPKWGJPGI5GUN4GZFZRWQFDG3RJNZJEIBYA7B3EPROG",
  "GAYYQCPTA52PUTTDDNFDX5FRPHQVTL5L7EJ7AZ7GBT5G36JTIAUMPDOC",
  "GA4KUJWJB5JVWPEN5JXZKUGHXTHQZYQOKU2VX2OG5MFDFLJEXT4DEACC",
  "GATEB4Y7IKPXLSRSTH5GOUYA4ZAS6KQVP32BDPFF3GMSFKRKOSAYSDFI",
  "GB52W5JF4FP4WTJQQINFVGEPLEVYZWIF62YZP677632L65R7QEYEMVPF",
  "GDMHOX27GXZFCDCYH3OXPA3OORSO55YR2WR42N3EFPRSL62BBVLEMVPM",
  "GD4H72QEA6Q5NKESCWLPVQJBCIWHXIUZEPTCIZUQSFR3AW3XBVB4MVPT",
  "GB4CFPKQI7MLLWESOV55GRHFS2JYVXFYK35B7EMAQ6ZZR7AASTASINTG",
]

[DOCUMENTATION]
ORG_NAME = "Programmers Guild of Montelibero Association"
ORG_URL = "https://mtlprog.xyz"

[[PRINCIPALS]]
name = "Stas Karkavin"
email = "stas@panarchy.now"
twitter = "staskarkavin"
github = "xdefrag"

[[CURRENCIES]]
code = "NUYEN"
issuer = "GDRLJC6EOKRR3BPKWGJPGI5GUN4GZFZRWQFDG3RJNZJEIBYA7B3EPROG"
display_decimals = 0

[[CURRENCIES]]
code = "MVP"
issuer = "GB52W5JF4FP4WTJQQINFVGEPLEVYZWIF62YZP677632L65R7QEYEMVPF"
display_decimals = 0

[[CURRENCIES]]
code = "INTG"
name = "INTG"
desc = "Integrality Bond"
issuer = "GB4CFPKQI7MLLWESOV55GRHFS2JYVXFYK35B7EMAQ6ZZR7AASTASINTG"
fixed_number = 10000
display_decimals = 7
image = "https://mtlprog.xyz/.well-known/integrality.png"

[[CURRENCIES]]
code = "MVPOffer"
issuer = "GD4H72QEA6Q5NKESCWLPVQJBCIWHXIUZEPTCIZUQSFR3AW3XBVB4MVPT"
fixed_number = 1
display_decimals = 7

[[CURRENCIES]]
code = "INTGE1"
name = "INTGE1"
desc = "Integrality Project Tokens Emission 1"
issuer = "GAYYQCPTA52PUTTDDNFDX5FRPHQVTL5L7EJ7AZ7GBT5G36JTIAUMPDOC"
fixed_number = 1
display_decimals = 7
image = "https://mtlprog.xyz/.well-known/integrality.png"
